version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: template1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ninja
    ports:
      - "5432:5432"
